<a href="https://colab.research.google.com/github/Mahabjan/PYTHON-PROGRAMMING/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Perform arithmetic operations on NumPy arrays.

In [13]:
import numpy as np

# Create two numpy arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 4, 3, 2, 1])

# Perform arithmetic operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
addition, subtraction, multiplication, division



(array([15, 24, 33, 42, 51]),
 array([ 5, 16, 27, 38, 49]),
 array([50, 80, 90, 80, 50]),
 array([ 2.,  5., 10., 20., 50.]))

2. Write a script to compute the mean and standard deviation of a NumPy array.

In [11]:
# Create a numpy array
arr = np.array([10, 20, 10, 40, 15])

# Compute mean and standard deviation
mean = np.mean(arr)
std_dev = np.std(arr)

print(f"Mean: {mean}")
print(f"Standard Deviation:{std_dev}")


Mean: 19.0
Standard Deviation:11.135528725660043


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [15]:
# Create the array with step size of 5
arr = np.arange(10, 51, 5)

print(arr)


[10 15 20 25 30 35 40 45 50]


4. Reshape the array into a 2x4 matrix.

In [19]:
import numpy as np

# Create an array with 8 elements
arr = np.array([10, 20, 30, 40, 50,60,70,80])

# Reshape the array into a 2x4 matrix
reshaped_arr = arr.reshape(2, 4)

# Display the reshaped array
print(reshaped_arr)


[[10 20 30 40]
 [50 60 70 80]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [21]:
# Create the array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract sub-matrix with last two rows and first two columns
sub_matrix = arr[1:, :2]

# Replace elements greater than 4 with 0
arr[arr > 4] = 0

print(sub_matrix)
print(arr)


[[4 0]
 [0 0]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division

In [22]:
# Create arrays a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
addition = a + b
multiplication = a * b
division = a / b

addition, multiplication, division


(array([5, 7, 9]), array([ 4, 10, 18]), array([0.25, 0.4 , 0.5 ]))

7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [23]:
# Create a random array of size (4, 4)
arr = np.random.randint(1, 100, size=(4, 4))

# Compute the mean of each column
column_mean = np.mean(arr, axis=0)

# Maximum value of the entire array
max_value = np.max(arr)

# Sum of all elements
sum_elements = np.sum(arr)

column_mean, max_value, sum_elements


(array([39.5 , 62.25, 58.75, 65.75]), 95, 905)

8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.


In [24]:
# Create the array
arr = np.array([1, 2, 3, 4])

# Add 10 to each element and multiply the result by 2
result = (arr + 10) * 2

print(result)


[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [25]:
# Create a 3D array of shape (3, 4, 5)
arr = np.random.randint(1, 100, size=(3, 4, 5))

# Extract the second "layer"
second_layer = arr[1, :, :]

# Extract the first two rows and last three columns from each "layer"
sliced_arr = arr[:, :2, -3:]

# Replace all elements divisible by 3 with -1
arr[arr % 3 == 0] = -1

second_layer, sliced_arr, arr


(array([[76, -1, 19, -1, 56],
        [70, 53, -1,  1, 49],
        [58, 64, 47, -1, -1],
        [-1, -1, -1, -1, 38]]),
 array([[[ 7, -1, -1],
         [11, -1, 22]],
 
        [[19, -1, 56],
         [-1,  1, 49]],
 
        [[-1, -1, 88],
         [-1, -1, 38]]]),
 array([[[68, 71,  7, -1, -1],
         [28, 25, 11, -1, 22],
         [-1, -1, -1, -1, 25],
         [31, 41, 58, -1, 37]],
 
        [[76, -1, 19, -1, 56],
         [70, 53, -1,  1, 49],
         [58, 64, 47, -1, -1],
         [-1, -1, -1, -1, 38]],
 
        [[62, 76, -1, -1, 88],
         [76, 23, -1, -1, 38],
         [-1, -1, 95, 95, -1],
         [64, 53, 20,  2,  1]]]))